implemented user interface
waheebh1/online-bookstore pull request #10
Opened 2023-11-09 03:31 UTC by waheebh1

2023-11-09 16:56 UTC, shrimeichock requested changes

2023-11-09 16:56 UTC, shrimeichock commented on src/main/resources/templates/checkout.html
> +    <style>
move styles to external style sheet

2023-11-09 16:56 UTC, shrimeichock commented on src/main/resources/templates/home.html
> +<html xmlns:th="http://www.thymeleaf.org">
add 'lang' attribute in html tags

2023-11-09 16:56 UTC, shrimeichock commented on src/main/resources/templates/home.html
> +        <form action="/addToCart" method="post">
should 'add/remove from cart' be buttons rather than forms?

2023-11-09 16:56 UTC, shrimeichock commented on src/main/resources/templates/home.html
> +        <form action="/removeFromCart" method="post">
should 'remove from cart' be moved to the checkout page where the cart items are displayed? That way, the user can adjust their cart before checking out

2023-11-09 16:56 UTC, shrimeichock commented on src/main/resources/templates/home.html
> +<!DOCTYPE HTML>
could you add another html page for each book. That way when you click on a book, you can see the info in more detail. Main list of books could just have a title, picture and price

2023-11-09 16:56 UTC, shrimeichock commented on src/main/resources/templates/home.html
> +        <h2><p class="books-quantity"></p></h2>
can't be a header and a paragraph

2023-11-09 16:56 UTC, shrimeichock commented on src/main/resources/templates/login.html
> +<head>
missing starting <html> tag

2023-11-09 16:56 UTC, shrimeichock commented on src/main/resources/templates/register-login.html
> +        <form action="register.html" method="get">
these should be buttons not forms because you're not submitting any info

2023-11-09 17:00 UTC, maishabd23 commented on src/main/resources/templates/home.html
> +        <form action="/removeFromCart" method="post">
I don't think it should entirely be removed, but maybe also a similar button on the checkout page per book user wants to remove from cart before checkout.

2023-11-09 21:06 UTC, shrimeichock requested changes

2023-11-09 21:06 UTC, shrimeichock commented on src/main/resources/templates/book-info.html
> +    <link rel="stylesheet" href="/src/main/java/public/stylesheets/general.css">
getting errors saying that these files could not be found. Could you double check that these are correct?

2023-11-09 21:06 UTC, shrimeichock commented on src/main/resources/templates/book-info.html
> +        <img src="book-image.jpg">
add 'alt' attribute for images

2023-11-09 21:06 UTC, shrimeichock commented on src/main/resources/templates/book-info.html
> +        <h1>Title: <h1 class="book-title"></h1></h1>
nested h1 and p tags

2023-11-09 23:16 UTC, waheebhashmi commented on src/main/resources/templates/book-info.html
> +    <link rel="stylesheet" href="/src/main/java/public/stylesheets/general.css">
it works on my side when i open the html file with a server, but doesnt work when i just double click on the files

2023-11-10 22:48 UTC, shrimeichock commented on src/main/resources/templates/book-info.html
> +    <link rel="stylesheet" href="/src/main/java/public/stylesheets/general.css">
I think it should be under the resources/static folder https://stackoverflow.com/questions/27170772/where-to-put-static-files-such-as-css-in-a-spring-boot-project

2023-11-10 22:56 UTC, shrimeichock commented on src/main/resources/templates/book-info.html
> +        <div class="book-year"></div>
the div should wrap around the actual object so that the classname tags actually apply. Seems as though you have empty divs right now

2023-11-10 23:03 UTC, waheebhashmi commented on src/main/resources/templates/book-info.html
> +        <div class="book-year"></div>
hmm, i think the point here is to load the div with JQuery as a single page application (similar to the idea in lab 6 part 2). That's why for now it would be empty

2023-11-11 15:31 UTC, thanujasiva requested changes

2023-11-11 15:31 UTC, thanujasiva commented on src/main/resources/templates/book-info.html
> +    <link rel="stylesheet" href="/src/main/resources/static/general.css">
I'm able to see the css work properly when I change the hrefs to this:
`href="../static/general.css"`

2023-11-11 15:31 UTC, thanujasiva commented on src/main/resources/templates/login.html
> +    <link rel="stylesheet" href="/src/main/resources/static/register-login.css">
Similarly, the register-login css works when I use this href:
`href="../static/register-login.css"`

2023-11-11 15:43 UTC, thanujasiva commented on src/main/resources/templates/book-info.html
> +    <link rel="stylesheet" href="/src/main/java/public/stylesheets/general.css">
My requested changes relate to this

2023-11-11 15:43 UTC, shrimeichock commented on src/main/resources/templates/book-info.html
> +        <div class="book-year"></div>
i see. in that case should the p tag for the Year be under the same div?

2023-11-11 16:45 UTC, thanujasiva commented on src/main/resources/templates/book-info.html
> +    <link rel="stylesheet" href="/src/main/resources/static/general.css">
We can make these changes in a later PR

2023-11-11 16:45 UTC, maishabd23 approved these changes

2023-11-11 16:46 UTC, thanujasiva approved these changes

2023-11-11 16:46 UTC, merged