Fixed add to cart and remove from cart
waheebh1/online-bookstore pull request #40
Opened 2023-11-21 17:24 UTC by maishabd23

![Screenshot (29)](https://github.com/waheebh1/online-bookstore/assets/59773012/08d40c33-93e3-4eaf-ba47-7ae8268002b0)

- Left system print statements in addToCart and removeFromCart methods in CheckoutController.java for debugging purposes - can remove later.

2023-11-21 18:25 UTC, shrimeichock requested changes

2023-11-21 18:25 UTC, shrimeichock commented on src/main/resources/templates/home.html
>      <a href="checkout.html">
checkout.html not found, reroutes to 404 error page

2023-11-21 18:25 UTC, shrimeichock commented on src/main/java/bookstore/inventory/CheckoutController.java
> +    @GetMapping("/addToCart")
what if i want to remove something from cart after adding the entire stock? the item disappears from list

2023-11-21 18:25 UTC, shrimeichock commented on src/main/java/bookstore/inventory/CartItem.java
> +    public CartItem(){
javadoc

2023-11-21 18:31 UTC, shrimeichock commented on src/main/resources/templates/home.html
>      <a href="checkout.html">
@waheebhashmi cover this in his PR

2023-11-21 18:39 UTC, shrimeichock commented on src/main/java/bookstore/inventory/CheckoutController.java
> +    @GetMapping("/addToCart")
will add an option to remove from cart on the checkout page.

2023-11-21 22:46 UTC, waheebhashmi commented on src/main/java/bookstore/inventory/CheckoutController.java
> +        ShoppingCart shoppingCart;
you can turn this into a separate method:
private ShoppingCart getOrCreateShoppingCart() {
    return shoppingCartRepository.findById(1)
                                 .orElseGet(() -> new ShoppingCart(inventoryRepository.findById(1)));
}

and just call it like so
ShoppingCart shoppingCart = getOrCreateShoppingCart();

2023-11-21 22:47 UTC, waheebhashmi commented on src/main/java/bookstore/inventory/CheckoutController.java
> +        List<BookUser> loggedInUsers = (List<BookUser>) loggedInUserRepository.findAll();
line 115 to line 119 could be turned to just one line    
BookUser loggedInUser = loggedInUserRepository.findFirst().orElse(null);

2023-11-21 22:49 UTC, waheebhashmi commented on src/main/java/bookstore/inventory/CheckoutController.java
> +        List<BookUser> loggedInUsers = (List<BookUser>) loggedInUserRepository.findAll();
same thing to the method below (removeFromCart)

2023-11-21 22:49 UTC, waheebhashmi commented on src/main/java/bookstore/inventory/CheckoutController.java
> +        ShoppingCart shoppingCart;
same thing to the method below (removeFromCart)

2023-11-22 13:40 UTC, shrimeichock approved these changes

2023-11-22 13:40 UTC, shrimeichock approved these changes

2023-11-22 13:47 UTC, thanujasiva requested changes

2023-11-22 13:47 UTC, thanujasiva commented on src/main/java/bookstore/inventory/Item.java
> +public class Item {
Can this be set as an abstract class? So it's obvious that objects shouldn't be created directly from this

Also, please remove the extra blank line above

2023-11-22 13:47 UTC, thanujasiva commented on src/main/java/bookstore/inventory/CartItem.java
> +public class CartItem extends Item {
Can be naming be changed to be consistent? For ex, either ShoppingCart and ShoppingCartItem, or Cart and CartItem

2023-11-22 13:48 UTC, thanujasiva commented on src/main/java/bookstore/inventory/CheckoutController.java
> +        List<BookUser> loggedInUsers = (List<BookUser>) loggedInUserRepository.findAll();
Didn't realize there was a findFirst method. Thanks for pointing this out!

2023-11-22 16:50 UTC, waheebhashmi commented on src/main/java/bookstore/inventory/CheckoutController.java
> +        ShoppingCart shoppingCart;
since orElseGet() doesnt work, you can just do:
return shoppingCartRepository.findById(1) != null ? shoppingCartRepository.findById(1) : new ShoppingCart(inventoryRepository.findById(1));

Inside getOrCreateShoppingCart()

2023-11-22 18:08 UTC, sabahsamwatin approved these changes

2023-11-23 00:16 UTC, maishabd23 commented on src/main/java/bookstore/inventory/CheckoutController.java
> +        ShoppingCart shoppingCart;
added.

2023-11-23 00:18 UTC, maishabd23 commented on src/main/java/bookstore/inventory/CheckoutController.java
> +        List<BookUser> loggedInUsers = (List<BookUser>) loggedInUserRepository.findAll();
is showing an error, kept it as is for now --> can be addressed in this [issue](https://github.com/users/waheebh1/projects/1/views/2?pane=issue&itemId=45354168)

2023-11-23 00:29 UTC, maishabd23 commented on src/main/java/bookstore/inventory/Item.java
> +public class Item {
done.

2023-11-23 00:29 UTC, maishabd23 commented on src/main/java/bookstore/inventory/CartItem.java
> +public class CartItem extends Item {
done.

2023-11-23 04:57 UTC, thanujasiva approved these changes

2023-11-23 16:55 UTC, merged