Upload Edit Functionality
waheebh1/online-bookstore pull request #79
Opened 2023-12-05 06:26 UTC by sabahsamwatin

Bookstore Owner can now:
- Upload a book that shows up on the homepage for the next Bookstore User.
- Edit a previously uploaded book details to change any of the provided information.

2023-12-05 18:23 UTC, shrimeichock commented
- "edit book" button disappearing after you edit book. Make sure you are returning to the viewbook endpoint
- when you create a book it only allows you to add integer prices, should be able to set the price to a float

2023-12-05 18:49 UTC, thanujasiva requested changes

2023-12-05 18:49 UTC, thanujasiva commented on src/main/java/bookstore/inventory/BookController.java
> +    public String showUploadForm(Model model) {
Can you add `HttpServletRequest request, HttpServletResponse response` to the header?

And then add this at the beginning of the method (make sure an owner is logged in):
```
        BookUser loggedInUser = userController.getLoggedInUser(request.getCookies());
        if(loggedInUser == null or !loggedInUser.getUserType(UserType.BOOKOWNER)){
            return "access-denied";
        }
```

2023-12-05 18:49 UTC, thanujasiva commented on src/main/java/bookstore/inventory/BookController.java
> +    public String showEditForm(@PathVariable String isbn, Model model) {
Add the same stuff with the request, response, and getLoggedInUser that I mentioned above.

2023-12-05 18:49 UTC, thanujasiva commented on src/main/java/bookstore/inventory/BookController.java
> +    public String showBookDetails(@PathVariable String isbn, Model model) {
Is it possible to combine this with the existing CheckoutController `viewBook` method?

That might be why the "edit" button didn't appear after submitting the edited changes.

2023-12-05 23:33 UTC, thanujasiva commented on src/main/java/bookstore/inventory/BookController.java
> +    public String showBookDetails(@PathVariable String isbn, Model model) {
Can you explain what the difference between the `showBookDetails` and `viewBook` methods are? Why do we need both of them?

2023-12-06 00:38 UTC, sabahsamwatin commented on src/main/java/bookstore/inventory/BookController.java
> +    public String showBookDetails(@PathVariable String isbn, Model model) {
I think userType might be different for showBookDetails and viewBook methods. First I thought there won't be any issue if I remove showBookDetails but after editing editing a book, clicking on Save Changes takes me to Whitelabel Error Page if I don't have showBookDetails method.

2023-12-06 01:48 UTC, thanujasiva requested changes

2023-12-06 01:48 UTC, thanujasiva commented on src/main/java/bookstore/inventory/BookController.java
> +            return "redirect:/book/info/" + book.getIsbn(); // redirect to the book detail page
If we want to keep the viewBook method, I think we can replace this line with:
```return "redirect:/viewBook?isbn=" + book.getIsbn();```

2023-12-06 01:48 UTC, thanujasiva commented on src/main/java/bookstore/inventory/CheckoutController.java
> +
Can you also add these lines in the `viewBook` method?

```
        String authors = bookToDisplay.getAuthor().stream()
                .map(author -> author.getFirstName() + " " + author.getLastName())
                .collect(Collectors.joining(", "));
        model.addAttribute("authors", authors);
```

2023-12-06 01:49 UTC, thanujasiva requested changes

2023-12-06 01:49 UTC, thanujasiva commented on src/main/java/bookstore/inventory/BookController.java
> +    public String showBookDetails(@PathVariable String isbn, Model model, HttpServletRequest request, HttpServletResponse response) {
If switching over to `viewBook` works, can this method be removed?

2023-12-06 02:09 UTC, thanujasiva commented
It looks like the upload/edit forms expect the date in a specific format. App.java doesn't follow this format, which means the date isn't filled in when editting those books.

* App.java seems to do DD/MM/YYYY
* The forms seems to require YYYY-MM-DD

In App.java, can you fix the date formats on the books? For example here: https://github.com/waheebh1/online-bookstore/blob/main/src/main/java/bookstore/App.java#L49

Change "11/07/1960" to "1960-07-11"

2023-12-06 02:18 UTC, thanujasiva approved these changes

2023-12-06 17:12 UTC, waheebhashmi approved these changes

2023-12-06 19:16 UTC, shrimeichock requested changes

2023-12-06 19:16 UTC, shrimeichock commented on src/main/resources/templates/uploadBook.html
> +      margin-bottom: 20px;
allows you to create multiple books with the same isbn. not sure why as the isbn has an @id tag so it should be unique

2023-12-06 19:16 UTC, shrimeichock commented on src/main/resources/templates/home.html
>      <h2>Total in Cart: <span th:id="totalInCart"></span></h2>
@shrimeichock showing empty checkbox for filtering when you add books without specifying publisher/genre

2023-12-06 19:16 UTC, shrimeichock commented on src/main/resources/templates/home.html
>      <h2>Total in Cart: <span th:id="totalInCart"></span></h2>
@shrimeichock not filtering for comma-separated authors. Book only showing up if you select all authors for that book

2023-12-06 19:16 UTC, shrimeichock commented on src/main/resources/templates/uploadBook.html
> +      background-color: white;
lets you put negative numbers and 0 for price

2023-12-06 19:16 UTC, shrimeichock commented on src/main/resources/templates/uploadBook.html
> +      margin: auto;
should be able to add multiples of a book, add as another field in the form

2023-12-06 19:16 UTC, shrimeichock commented on src/main/resources/templates/uploadBook.html
> +    .form-row {
optionally add a button for user to remove a book, if time permits

2023-12-06 20:40 UTC, shrimeichock commented on src/main/resources/templates/home.html
>      <h2>Total in Cart: <span th:id="totalInCart"></span></h2>
for the second issues, just make sure to add a first and last name for the author. otherwise, it will add an empty string as the lastname which messes up the filter. can fix to force user to add lastname if time permits

2023-12-06 21:28 UTC, sabahsamwatin commented on src/main/resources/templates/uploadBook.html
> +      background-color: white;
Solved [Price should be positive](https://github.com/waheebh1/online-bookstore/pull/79/commits/c30830a92c6b31d305997153f9dc76832550238b)

2023-12-06 21:29 UTC, sabahsamwatin commented on src/main/resources/templates/uploadBook.html
> +      margin: auto;
Solved [Added quantity for uploading and editing multiples of books](https://github.com/waheebh1/online-bookstore/pull/79/commits/a6b40f4ace76d474001a74136a500f5b3b359334)

2023-12-06 23:26 UTC, sabahsamwatin commented on src/main/resources/templates/home.html
>      <h2>Total in Cart: <span th:id="totalInCart"></span></h2>
Solved [Uploaded author names should have First and Last name for Filtering t…](https://github.com/waheebh1/online-bookstore/pull/79/commits/1590f4a4a4f7631d5b9ccee8562ea98cab5153dc)

2023-12-07 01:13 UTC, sabahsamwatin commented on src/main/resources/templates/uploadBook.html
> +      margin-bottom: 20px;
Solved! [Fixed ISBN, added Error Messages](https://github.com/waheebh1/online-bookstore/pull/79/commits/0825f6a0a0125858151603c4ea2cee5637b74f85)

2023-12-07 02:23 UTC, shrimeichock approved these changes

2023-12-07 02:27 UTC, merged