Cart tests
waheebh1/online-bookstore pull request #87
Opened 2023-12-06 19:17 UTC by maishabd23

2023-12-06 23:46 UTC, thanujasiva requested changes

2023-12-06 23:46 UTC, thanujasiva commented on pom.xml
> +          <groupId>org.mockito</groupId>
Could this dependency be removed if the tests work without it?

2023-12-06 23:57 UTC, maishabd23 commented on pom.xml
> +          <groupId>org.mockito</groupId>
removed

2023-12-07 00:09 UTC, thanujasiva approved these changes

2023-12-07 00:11 UTC, merged